/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsFireHydrantRouteImport } from './routes/products.fire-hydrant'
import { Route as ProductsFireExtinguisherRouteImport } from './routes/products.fire-extinguisher'
import { Route as ProductsFireAlarmRouteImport } from './routes/products.fire-alarm'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFireHydrantRoute = ProductsFireHydrantRouteImport.update({
  id: '/products/fire-hydrant',
  path: '/products/fire-hydrant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFireExtinguisherRoute =
  ProductsFireExtinguisherRouteImport.update({
    id: '/products/fire-extinguisher',
    path: '/products/fire-extinguisher',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductsFireAlarmRoute = ProductsFireAlarmRouteImport.update({
  id: '/products/fire-alarm',
  path: '/products/fire-alarm',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/products/fire-alarm': typeof ProductsFireAlarmRoute
  '/products/fire-extinguisher': typeof ProductsFireExtinguisherRoute
  '/products/fire-hydrant': typeof ProductsFireHydrantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/products/fire-alarm': typeof ProductsFireAlarmRoute
  '/products/fire-extinguisher': typeof ProductsFireExtinguisherRoute
  '/products/fire-hydrant': typeof ProductsFireHydrantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/products/fire-alarm': typeof ProductsFireAlarmRoute
  '/products/fire-extinguisher': typeof ProductsFireExtinguisherRoute
  '/products/fire-hydrant': typeof ProductsFireHydrantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/products/fire-alarm'
    | '/products/fire-extinguisher'
    | '/products/fire-hydrant'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/products/fire-alarm'
    | '/products/fire-extinguisher'
    | '/products/fire-hydrant'
  id:
    | '__root__'
    | '/'
    | '/privacy'
    | '/terms'
    | '/products/fire-alarm'
    | '/products/fire-extinguisher'
    | '/products/fire-hydrant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  ProductsFireAlarmRoute: typeof ProductsFireAlarmRoute
  ProductsFireExtinguisherRoute: typeof ProductsFireExtinguisherRoute
  ProductsFireHydrantRoute: typeof ProductsFireHydrantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/fire-hydrant': {
      id: '/products/fire-hydrant'
      path: '/products/fire-hydrant'
      fullPath: '/products/fire-hydrant'
      preLoaderRoute: typeof ProductsFireHydrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/fire-extinguisher': {
      id: '/products/fire-extinguisher'
      path: '/products/fire-extinguisher'
      fullPath: '/products/fire-extinguisher'
      preLoaderRoute: typeof ProductsFireExtinguisherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/fire-alarm': {
      id: '/products/fire-alarm'
      path: '/products/fire-alarm'
      fullPath: '/products/fire-alarm'
      preLoaderRoute: typeof ProductsFireAlarmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  ProductsFireAlarmRoute: ProductsFireAlarmRoute,
  ProductsFireExtinguisherRoute: ProductsFireExtinguisherRoute,
  ProductsFireHydrantRoute: ProductsFireHydrantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
