/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsFireHydrantRouteImport } from './routes/products.fire-hydrant'
import { Route as ProductsFireExtinguisherRouteImport } from './routes/products.fire-extinguisher'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFireHydrantRoute = ProductsFireHydrantRouteImport.update({
  id: '/products/fire-hydrant',
  path: '/products/fire-hydrant',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFireExtinguisherRoute =
  ProductsFireExtinguisherRouteImport.update({
    id: '/products/fire-extinguisher',
    path: '/products/fire-extinguisher',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/fire-extinguisher': typeof ProductsFireExtinguisherRoute
  '/products/fire-hydrant': typeof ProductsFireHydrantRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/fire-extinguisher': typeof ProductsFireExtinguisherRoute
  '/products/fire-hydrant': typeof ProductsFireHydrantRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/fire-extinguisher': typeof ProductsFireExtinguisherRoute
  '/products/fire-hydrant': typeof ProductsFireHydrantRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/products/fire-extinguisher' | '/products/fire-hydrant'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/products/fire-extinguisher' | '/products/fire-hydrant'
  id:
    | '__root__'
    | '/'
    | '/products/fire-extinguisher'
    | '/products/fire-hydrant'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsFireExtinguisherRoute: typeof ProductsFireExtinguisherRoute
  ProductsFireHydrantRoute: typeof ProductsFireHydrantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/fire-hydrant': {
      id: '/products/fire-hydrant'
      path: '/products/fire-hydrant'
      fullPath: '/products/fire-hydrant'
      preLoaderRoute: typeof ProductsFireHydrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/fire-extinguisher': {
      id: '/products/fire-extinguisher'
      path: '/products/fire-extinguisher'
      fullPath: '/products/fire-extinguisher'
      preLoaderRoute: typeof ProductsFireExtinguisherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsFireExtinguisherRoute: ProductsFireExtinguisherRoute,
  ProductsFireHydrantRoute: ProductsFireHydrantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
